public enum TokenType {
    AS, AND, BREAK, CONTINUE, DEF, ELSE, ELIF, IF, FALSE, TRUE,
    NONE, WITH, FOR, IN, IS, NOR, NOT, RETURN, WHILE, IDENTIFIER,
    STRING, INTEGER, FLOAT, PLUS, MINUS, MULTIPLICATION, DIVIDE, ASSIGNMENT,
    LEFT_CBRACE, RIGHT_CBRACE, LEFT_BRACE, RIGHT_BRACE, SEMICOLON, COLON
}
